name: "test"

on:
  push:
    branches:
      - main
      - pcheremu-add-allure
  workflow_dispatch:
    inputs:
      TEST_ENDPOINT: #this is used as ENV variable to provide host to run tests for
        description: "Endpoint for tests"
        required: true
        default: https://dev.github.com
      TEST_BROWSER: #this is used as ENV variable to browser to run tests with
        description: "Browser for tests"
        required: true
        default: chrome
      ALLURE_JOB_RUN_ID: # this will be used to generate Launch name on Allure TestOps side
        description: "Inner parameter for Allure TestOps"
        required: false

env:
  ALLURE_ENDPOINT: ${{ secrets.ALLURE_ENDPOINT }}
  ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
  ALLURE_PROJECT_ID: ${{ secrets.ALLURE_PROJECT_ID }}
  ALLURE_TESTPLAN_PATH: "./testplan.json" # needed to filter the tests
  ALLURE_RESULTS: "allure-results" # folder with the test results
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }} 

jobs:
  wallet:
    name: "Launch testing"
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        
      - name: actions/checkout@v2
        uses: actions/checkout@v2
      
      - name: yarn install --immutable
        run: yarn install --immutable # this is needed to run chromium (puppeteer / dappeteer) with metamask extension
  
      - name: Yarn version
        run: yarn --version
  
      - name: Install setup-node
        uses: actions/setup-node@v1
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
        with:
          args: install

      - name: Download allurectl
        run: wget https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_386 -O ./allurectl

      - name: Change permission for allurectl
        run: chmod +x ./allurectl
          
      - name: Prepare TestPlan
        run: ./allurectl job-run plan --output-file ${ALLURE_TESTPLAN_PATH}
   
      - name: Echo
        run: echo ${ALLURE_JOB_RUN_ID}
  
      - name: Launch tests
        uses: mujo-code/puppeteer-headful@8baa091f83c74d2eda8603b7f9990b20535e7a9c
        env:
          CI: 'true'
        with:
          args: yarn test

      - name: Show files after
        run: ls -a
  
      - name: Upload tests
        uses: mujo-code/puppeteer-headful@8baa091f83c74d2eda8603b7f9990b20535e7a9c
        env:
          ALLURE_JOB_UID: ${{steps.allure-job-uid.outputs.result}}
        with:
          args: ./allurectl upload --launch-name "test 2022" ${ALLURE_RESULTS}  # allows sending the test results in the real time
          # args: ./allurectl watch --results ${ALLURE_RESULTS} -- yarn test # allows sending the test results in the real time

      - name: Save artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: wallet-artifacts_${{ github.run_number }}_${{ steps.date.outputs.date }}
          path: artifacts/*
          
